export const dummyBooks = [
    { id: 1, title: "The Great Gatsby", image: "https://i0.wp.com/americanwritersmuseum.org/wp-content/uploads/2018/02/CK-3.jpg?resize=267%2C400&ssl=1" },
    { id: 2, title: "Moby Dick", image: "/placeholder.svg?height=200&width=150" },
    { id: 3, title: "1984", image: "https://images.booksense.com/images/333/869/9781328869333.jpg" },
    { id: 4, title: "Pride and Prejudice", image: "/placeholder.svg?height=200&width=150" },
    { id: 5, title: "To Kill a Mockingbird", image: "/placeholder.svg?height=200&width=150" },
    { id: 6, title: "War and Peace", image: "/placeholder.svg?height=200&width=150" },
    { id: 7, title: "The Catcher in the Rye", image: "/placeholder.svg?height=200&width=150" },
    { id: 8, title: "The Odyssey", image: "/placeholder.svg?height=200&width=150" },
    { id: 9, title: "Jane Eyre", image: "/placeholder.svg?height=200&width=150" },
    { id: 10, title: "Crime and Punishment", image: "/placeholder.svg?height=200&width=150" },
    { id: 11, title: "Brave New World", image: "/placeholder.svg?height=200&width=150" },
    { id: 12, title: "The Hobbit", image: "/placeholder.svg?height=200&width=150" },
    { id: 13, title: "The Lord of the Rings", image: "/placeholder.svg?height=200&width=150" },
    { id: 14, title: "Animal Farm", image: "/placeholder.svg?height=200&width=150" },
    { id: 15, title: "The Picture of Dorian Gray", image: "/placeholder.svg?height=200&width=150" },
    { id: 16, title: "Wuthering Heights", image: "/placeholder.svg?height=200&width=150" },
    { id: 17, title: "The Brothers Karamazov", image: "/placeholder.svg?height=200&width=150" },
    { id: 18, title: "The Scarlet Letter", image: "/placeholder.svg?height=200&width=150" },
    { id: 19, title: "The Grapes of Wrath", image: "/placeholder.svg?height=200&width=150" },
    { id: 20, title: "The Catcher in the Rye", image: "/placeholder.svg?height=200&width=150" },
    { id: 21, title: "Fahrenheit 451", image: "/placeholder.svg?height=200&width=150" },
    { id: 22, title: "The Shining", image: "/placeholder.svg?height=200&width=150" },
    { id: 23, title: "Frankenstein", image: "/placeholder.svg?height=200&width=150" },
    { id: 24, title: "Dracula", image: "/placeholder.svg?height=200&width=150" },
    { id: 25, title: "The Hunger Games", image: "/placeholder.svg?height=200&width=150" },
    { id: 26, title: "The Alchemist", image: "/placeholder.svg?height=200&width=150" },
    { id: 27, title: "The Da Vinci Code", image: "/placeholder.svg?height=200&width=150" },
    { id: 28, title: "The Road", image: "/placeholder.svg?height=200&width=150" },
    { id: 29, title: "The Fault in Our Stars", image: "/placeholder.svg?height=200&width=150" },
    { id: 30, title: "The Night Circus", image: "/placeholder.svg?height=200&width=150" },
    { id: 31, title: "The Girl on the Train", image: "/placeholder.svg?height=200&width=150" },
    { id: 32, title: "Gone with the Wind", image: "/placeholder.svg?height=200&width=150" },
    { id: 33, title: "The Bell Jar", image: "/placeholder.svg?height=200&width=150" },
    { id: 34, title: "The Outsiders", image: "/placeholder.svg?height=200&width=150" },
    { id: 35, title: "The Secret Garden", image: "/placeholder.svg?height=200&width=150" },
    { id: 36, title: "Little Women", image: "/placeholder.svg?height=200&width=150" },
    { id: 37, title: "The Sun Also Rises", image: "/placeholder.svg?height=200&width=150" },
    { id: 38, title: "Les Misérables", image: "/placeholder.svg?height=200&width=150" },
    { id: 39, title: "A Tale of Two Cities", image: "https://images.penguinrandomhouse.com/cover/9780451530578" },
    { id: 40, title: "Sapiens: A Brief History of Humankind", image: "/placeholder.svg?height=200&width=150" },
    { id: 41, title: "Educated", image: "/placeholder.svg?height=200&width=150" },
    { id: 42, title: "Becoming", image: "/placeholder.svg?height=200&width=150" },
    { id: 43, title: "Where the Crawdads Sing", image: "/placeholder.svg?height=200&width=150" },
    { id: 44, title: "Circe", image: "/placeholder.svg?height=200&width=150" },
    { id: 45, title: "The Nightingale", image: "/placeholder.svg?height=200&width=150" },
    { id: 46, title: "Big Little Lies", image: "/placeholder.svg?height=200&width=150" },
    { id: 47, title: "The Help", image: "/placeholder.svg?height=200&width=150" },
    { id: 48, title: "The Silent Patient", image: "/placeholder.svg?height=200&width=150" },
    { id: 49, title: "Sharp Objects", image: "/placeholder.svg?height=200&width=150" },
    { id: 50, title: "Normal People", image: "/placeholder.svg?height=200&width=150" }
  ];
  